services:
  backend:
    build: ./Backend
    container_name: ai-review-backend

    env_file:
      - ./Backend/.env

    ports:
      - "5000:5000"

    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: ai-review-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped