version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: ai-review-backend

    ports:
      - "5000:5000"

    env_file:
      - ./Backend/.env

    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: ai-review-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: unless-stopped
